/*
 * MainFrame.java
 *
 * Created on 24. November 2006, 11:31
 */

package visabsorber;

import java.awt.Dimension;
import java.io.File;
import java.text.DateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author  Jan-Stefan Fischer
 */
public class MainFrame extends javax.swing.JFrame {
    ElementList elementList = new ElementList();
    NodeList nodeList = new NodeList();
    LineList lineList = new LineList();
    int cut=0, cutCount=0, it;
    double absLength=0, cpWater=0, massflow=0, lAbs,lDam,lBod,tU,tF,q,aU,aF,res;
    public MainFrame() {
        initComponents();
        scrollPane1.add(visMatrix);
        //jScrollPane2.add(visMatrix);
        visMatrix.setSize(new Dimension(5000,5000));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel2 = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        statusBar = new javax.swing.JProgressBar();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        scrollPane1 = new java.awt.ScrollPane();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rbdFileField = new javax.swing.JTextField();
        elementFileField = new javax.swing.JTextField();
        nodeFileField = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("visAbsorber");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        statusLabel.setText("Status");

        jButton6.setText("zoom +10");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("zoom -10");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jToggleButton1.setText("show Grid");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jButton5.setText("refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton8.setText("save");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(scrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, statusLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                    .add(statusBar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jButton6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton7)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jToggleButton1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton5)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton8)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(statusLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(statusBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(11, 11, 11)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton7)
                    .add(jToggleButton1)
                    .add(jButton6)
                    .add(jButton5)
                    .add(jButton8))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(scrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setAutoscrolls(true);
        jLabel8.setText("Elementenliste");

        jLabel9.setText("Randbedingungsliste");

        rbdFileField.setText("D:\\Programmierung\\PPM\\Auswertung\\matlab\\Grid_10\\grid.rbd");

        elementFileField.setText("D:\\Programmierung\\PPM\\Auswertung\\matlab\\Grid_10\\grid.ele");

        nodeFileField.setText("D:\\Programmierung\\PPM\\Auswertung\\matlab\\Grid_10\\grid.knt");

        jButton3.setText("...");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("...");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setText("Knotenliste");

        jButton1.setText("start FEM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("W\u00e4rmeleitf\u00e4higkeit (Boden):");

        jLabel3.setText("W\u00e4rmeleitf\u00e4higkeit (D\u00e4mmung):");

        jLabel6.setText("Umgebungstemperatur:");

        jLabel1.setText("Absorbereigenschaften:");

        jLabel5.setText("Umgebungseigenschaften:");

        jTextField4.setText("20");

        jTextField3.setText("200");

        jTextField2.setText("0.04");

        jTextField1.setText("380");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("W\u00e4rmeleitf\u00e4higkeit (Platte+Rohr):");

        jLabel10.setText("W\u00e4rme\u00fcbergang an Umgebung:");

        jTextField5.setText("20");

        jLabel11.setText("Wassertemperatur:");

        jTextField6.setText("15");

        jLabel12.setText("W\u00e4rme\u00fcbergang an Wasser:");

        jTextField7.setText("60");

        jLabel13.setText("W\u00e4rmestromdichte durch Strahlung:");

        jTextField8.setText("1300");

        jLabel14.setText("FEM-Eigenschaften");

        jLabel15.setText("Anzahl der Ittartionen:");

        jTextField9.setText("100000000");

        jLabel16.setText("Maximales Resdiuum:");

        jTextField10.setText("0.00000000000001");

        jLabel17.setText("Massenstrom Wasser:");

        jTextField11.setText("0.01");

        jLabel18.setText("W\u00e4rmekapazit\u00e4t Wasser:");

        jTextField12.setText("4170");

        jLabel19.setText("L\u00e4nge des Absorbers:");

        jLabel20.setText("Anzahl der Schnitte:");

        jTextField13.setText("10");

        jTextField14.setText("7");

        jButton9.setText("start FEM-Test-Gebiet");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel7)
                            .add(jLabel8)
                            .add(jLabel9)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, rbdFileField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, elementFileField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                                    .add(nodeFileField, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(jButton3)
                                        .add(jButton2))
                                    .add(jButton4)))))
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel1))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jTextField1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                            .add(jLabel2)
                            .add(jLabel3)
                            .add(jTextField2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                            .add(jLabel4)
                            .add(jTextField3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel5)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(10, 10, 10)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jTextField4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                                    .add(jLabel6)
                                    .add(jLabel10)
                                    .add(jTextField5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                                    .add(jLabel11)
                                    .add(jTextField6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                                    .add(jLabel12)
                                    .add(jTextField7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                                    .add(jLabel13)
                                    .add(jTextField8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                                    .add(jLabel17)
                                    .add(jTextField11, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                                    .add(jLabel18)
                                    .add(jTextField12, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                                    .add(jLabel19)
                                    .add(jTextField14, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)))))
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jTextField13, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel14)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(10, 10, 10)
                                        .add(jLabel20)))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 261, Short.MAX_VALUE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jTextField9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                .add(10, 10, 10)
                                .add(jLabel15)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 248, Short.MAX_VALUE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(10, 10, 10)
                                .add(jLabel16)
                                .add(170, 170, 170))
                            .add(jTextField10, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                            .add(jButton1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jButton9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel7)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton2)
                    .add(nodeFileField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(6, 6, 6)
                .add(jLabel8)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(elementFileField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel9)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(rbdFileField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton4))
                .add(26, 26, 26)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(17, 17, 17)
                .add(jLabel5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel6)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel10)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextField5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel11)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextField6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel12)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextField7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel13)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextField8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel17)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextField11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel18)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextField12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel19)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextField14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(20, 20, 20)
                .add(jLabel14)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel20)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextField13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel15)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextField9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel16)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextField10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton9)
                .addContainerGap(299, Short.MAX_VALUE))
        );
        jScrollPane1.setViewportView(jPanel1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(1, 1, 1)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        nodeList = ReadFile.loadNodesFromFile(new File(nodeFileField.getText()));
        if (nodeList != null) {
            elementList = ReadFile.loadElementsFromFile(new File(elementFileField.getText()), nodeList);
            if (elementList != null) {
                lineList = ReadFile.loadLinesFromFile(new File(rbdFileField.getText()), nodeList);
                if (lineList == null) {
                    JOptionPane.showMessageDialog(null, "Fehler beim einlesen der Randliste","Fehler", JOptionPane.ERROR_MESSAGE);
                } else {
//JOptionPane.showMessageDialog(null, "Fertig","Fertig", JOptionPane.ERROR_MESSAGE);
                    /*lAbs=Double.valueOf(jTextField1.getText()).doubleValue();
                    lDam=Double.valueOf(jTextField2.getText()).doubleValue();
                    lBod=Double.valueOf(jTextField3.getText()).doubleValue();
                    tU=Double.valueOf(jTextField4.getText()).doubleValue();
                    tF=Double.valueOf(jTextField6.getText()).doubleValue();
                    q=Double.valueOf(jTextField8.getText()).doubleValue();
                    aU=Double.valueOf(jTextField5.getText()).doubleValue();
                    aF=Double.valueOf(jTextField7.getText()).doubleValue();*/
                     
                    it=Double.valueOf(jTextField9.getText()).intValue();
                    res=Double.valueOf(jTextField10.getText()).doubleValue();
                    cut=0;
                    cutCount=0;
                    /*cpWater=Double.valueOf(jTextField12.getText()).doubleValue();
                    massflow=Double.valueOf(jTextField11.getText()).doubleValue();
                    absLength=Double.valueOf(jTextField14.getText()).doubleValue();*/
                    
                    for (int i = 0; i < elementList.getCount(); i++) {
                        Element e = elementList.getElement(i);
                        e.setlamda(100);
                    }
                    
                    for (int i = 0; i < lineList.getCount(); i++) {
                        Line line = lineList.getLine(i);
                        switch (line.getType()) {
                            case 0: line.setProperties(false,0,false,0,0);
                                    line.getNode0().setU(20);
                                    line.getNode1().setU(20);
                            
                            break;
                            case 1: line.setProperties(true,0,false,aF,tF);
                            break;
                            case 2: line.setProperties(true,0,false,aU,tU);
                            //line.getNode0().setU(20.0);
                            //line.getNode1().setU(20.0);
                            break;
                            case 3: line.setProperties(false,0,true,400,0);
                            break;
                       
                        }
                    }
                    //nodeList.getNode(10).setU(80.0);
                      Matrix VectorX = new Matrix(1,nodeList.getCount());
        //calc.calcLUShort (S, p, VectorX);
                    for (int i=0;i<VectorX.getYCount();i++) {
                         VectorX.setValue(0,i,20.0);
                    }    
                    FEM fem= new FEM(nodeList, elementList, lineList, this, it,res,VectorX);
                    try {
                        fem.join();
                    } catch (Exception exc) {
                        JOptionPane.showMessageDialog(null, exc.getMessage() , "Fehler", JOptionPane.ERROR_MESSAGE);
                    }
                    fem = new FEM(nodeList, elementList, lineList, this, it,res,VectorX);
                    fem.start();
                    //if (X!=null)  X.saveMatrixToFile(new File("x.txt"));
                    //visMatrix.repaint();
                }
            } else JOptionPane.showMessageDialog(null, "Fehler beim einlesen der Elementenliste","Fehler", JOptionPane.ERROR_MESSAGE);
        } else JOptionPane.showMessageDialog(null, "Fehler beim einlesen der Knotenliste","Fehler", JOptionPane.ERROR_MESSAGE);
      
    }//GEN-LAST:event_jButton9ActionPerformed
    
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        visMatrix.save();
    }//GEN-LAST:event_jButton8ActionPerformed
    
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
// TODO add your handling code here:
        visMatrix.changeGridView();
        femFinish(null);
    }//GEN-LAST:event_jToggleButton1ActionPerformed
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        visMatrix.zoomMinus();
        femFinish(null);
    }//GEN-LAST:event_jButton7ActionPerformed
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        visMatrix.zoomPlus();
        femFinish(null);
    }//GEN-LAST:event_jButton6ActionPerformed
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        femFinish(null);
        
        /*nodeList=loadNodesFromFile(new File(nodeFileField.getText()));
        JOptionPane.showMessageDialog(null, ""+nodeList.getCount(), "Fehler Elementenliste", JOptionPane.ERROR_MESSAGE);
        elementList=loadElementsFromFile(new File(elementFileField.getText()));*/
        
    }//GEN-LAST:event_jButton5ActionPerformed
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        rbdFileField.setText(ReadFile.openDialog().toString());
    }//GEN-LAST:event_jButton4ActionPerformed
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        elementFileField.setText(ReadFile.openDialog().toString());
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        nodeFileField.setText(ReadFile.openDialog().toString());
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        nodeList = ReadFile.loadNodesFromFile(new File(nodeFileField.getText()));
        if (nodeList != null) {
            elementList = ReadFile.loadElementsFromFile(new File(elementFileField.getText()), nodeList);
            if (elementList != null) {
                lineList = ReadFile.loadLinesFromFile(new File(rbdFileField.getText()), nodeList);
                if (lineList == null) {
                    JOptionPane.showMessageDialog(null, "Fehler beim einlesen der Randliste","Fehler", JOptionPane.ERROR_MESSAGE);
                } else {
//JOptionPane.showMessageDialog(null, "Fertig","Fertig", JOptionPane.ERROR_MESSAGE);
                    lAbs=Double.valueOf(jTextField1.getText()).doubleValue();
                    lDam=Double.valueOf(jTextField2.getText()).doubleValue();
                    lBod=Double.valueOf(jTextField3.getText()).doubleValue();
                    tU=Double.valueOf(jTextField4.getText()).doubleValue();
                    tF=Double.valueOf(jTextField6.getText()).doubleValue();
                    q=Double.valueOf(jTextField8.getText()).doubleValue();
                    aU=Double.valueOf(jTextField5.getText()).doubleValue();
                    aF=Double.valueOf(jTextField7.getText()).doubleValue();
                    it=Double.valueOf(jTextField9.getText()).intValue();
                    res=Double.valueOf(jTextField10.getText()).doubleValue();
                    cut=0;
                    cutCount=Integer.valueOf(jTextField13.getText()).intValue();
                    cpWater=Double.valueOf(jTextField12.getText()).doubleValue();
                    massflow=Double.valueOf(jTextField11.getText()).doubleValue();
                    absLength=Double.valueOf(jTextField14.getText()).doubleValue();
                    
                    for (int i = 0; i < elementList.getCount(); i++) {
                        Element e = elementList.getElement(i);
                        switch (e.getMatirial()) {
                            case 0: e.setlamda(lAbs);
                            break;
                            case 1: e.setlamda(lDam);
                            break;
                            case 2: e.setlamda(lBod);
                            break;
                        }
                    }
                    
                    for (int i = 0; i < lineList.getCount(); i++) {
                        Line line = lineList.getLine(i);
                        switch (line.getType()) {
                            case 0: line.setProperties(true,q,false,0,0);
                            //line.getNode0().setU(80.0);
                            //line.getNode1().setU(80.0);
                            break;
                            case 1: line.setProperties(false,0,true,aF,tF);
                            break;
                            case 2: line.setProperties(false,0,true,aU,tU);
                            //line.getNode0().setU(20.0);
                            //line.getNode1().setU(20.0);
                            break;
                            case 3: line.setProperties(true,0,false,0,0);
                            break;
                            case 4: line.setProperties(true,0,false,0,0);
                            break;
                        }
                    }
                    //nodeList.getNode(10).setU(80.0);
                      Matrix VectorX = new Matrix(1,nodeList.getCount());
        //calc.calcLUShort (S, p, VectorX);
                    for (int i=0;i<VectorX.getYCount();i++) {
                         VectorX.setValue(0,i,20.0);
                    }    
                    FEM fem= new FEM(nodeList, elementList, lineList, this, it,res,VectorX);
                    try {
                        fem.join();
                    } catch (Exception exc) {
                        JOptionPane.showMessageDialog(null, exc.getMessage() , "Fehler", JOptionPane.ERROR_MESSAGE);
                    }
                    fem = new FEM(nodeList, elementList, lineList, this, it,res,VectorX);
                    fem.start();
                    //if (X!=null)  X.saveMatrixToFile(new File("x.txt"));
                    //visMatrix.repaint();
                }
            } else JOptionPane.showMessageDialog(null, "Fehler beim einlesen der Elementenliste","Fehler", JOptionPane.ERROR_MESSAGE);
        } else JOptionPane.showMessageDialog(null, "Fehler beim einlesen der Knotenliste","Fehler", JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void femFinish(Matrix VectorX) {
        double qRohr=0;
        double qOberfl=0;
        double qLuft=0;
        for (int i=0;i<lineList.getCount();i++) {
            Line line = lineList.getLine(i);
            if (line.getType()==0) {
                qOberfl=qOberfl+line.getQProMeter();
            }
            if (line.getType()==1) {
                qRohr=qRohr+line.getQProMeter();
            }
            if (line.getType()==2) {
                qLuft=qLuft+line.getQProMeter();
            }
        }
       
            visMatrix.refreshImg(nodeList, elementList, lineList, qRohr, qOberfl, qLuft, tF, absLength);
            visMatrix.repaint();
            Date today;
            String dateOut;
        

            DateFormat formatter = DateFormat.getDateTimeInstance(DateFormat.SHORT,
                                   DateFormat.SHORT,
                                   Locale.US);
            today = new Date();
            dateOut = formatter.format(today);
                    
        if (cut<cutCount) {
            tF = tF-(qRohr*absLength/cutCount)/(cpWater*massflow);
            visMatrix.refreshImg(nodeList, elementList, lineList, qRohr, qOberfl, qLuft, tF, absLength/cutCount*cut);
            visMatrix.repaint();
            visMatrix.saveToFile(new File("Bilder\\"+dateOut+"\\"+cut+".png"));
            cut++;
            nodeList.resetNodeList();
            tF = tF-(qRohr*absLength/cutCount)/(cpWater*massflow);
            for (int i = 0; i < lineList.getCount(); i++) {
                Line line = lineList.getLine(i);
                switch (line.getType()) {
                    case 1: line.setProperties(false,0,true,aF,tF);
                    break;
                }
                
            }
            FEM fem= new FEM(nodeList, elementList, lineList, this, it,res,VectorX);
            try {
                fem.join();
            } catch (Exception exc) {
                JOptionPane.showMessageDialog(null, exc.getMessage() , "Fehler", JOptionPane.ERROR_MESSAGE);
            }
            fem = new FEM(nodeList, elementList, lineList, this, it,res,VectorX);
            fem.start();
        }
        else {

            visMatrix.saveToFile(new File(""+cut+".png"));
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField elementFileField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField nodeFileField;
    private javax.swing.JTextField rbdFileField;
    private java.awt.ScrollPane scrollPane1;
    public javax.swing.JProgressBar statusBar;
    public javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
    public MyCanvas visMatrix = new MyCanvas(nodeList, elementList, lineList);
}
