/*
 * MainFrame.java
 *
 * Created on 24. November 2006, 11:31
 */

package visabsorber;

import javax.swing.JOptionPane;

/**
 *
 * @author  Jan-Stefan Fischer
 */
public class MainFrame extends javax.swing.JFrame {
    
    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        startFEM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        startFEM.setText("start FEM");
        startFEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startFEMActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(startFEM)
                .addContainerGap(311, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(startFEM)
                .addContainerGap(266, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startFEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startFEMActionPerformed
// TODO add your handling code here:
        ElementList elementList = new ElementList();
        NodeList nodeList = new NodeList();
        LineList lineList = new LineList();
        nodeList.addNode(new Node(0.0,0.0,10.0,true,0));
        nodeList.addNode(new Node(0.0,10.0,10.0,true,1));
        nodeList.addNode(new Node(0.1,5.0,0.0,false,2));
        nodeList.addNode(new Node(10.0,0.0,0.0,false,3));
        nodeList.addNode(new Node(10.0,10.0,0.0,false,4));
        lineList.addLine(new Line (nodeList.getNode(0),nodeList.getNode(1),true,10.0,false,0,0));
        lineList.addLine(new Line (nodeList.getNode(3),nodeList.getNode(4),true,-10.0,false,0,0));
        elementList.addElement(new Element(nodeList.getNode(0),nodeList.getNode(2),nodeList.getNode(1),1,0,0,0));
        elementList.addElement(new Element(nodeList.getNode(0),nodeList.getNode(3),nodeList.getNode(2),1,0,0,1));
        elementList.addElement(new Element(nodeList.getNode(3),nodeList.getNode(4),nodeList.getNode(2),1,0,0,2));
        elementList.addElement(new Element(nodeList.getNode(2),nodeList.getNode(4),nodeList.getNode(1),1,0,0,3));
        FEM fem= new FEM(nodeList, elementList, lineList);
        Matrix X=fem.calcX();
        JOptionPane.showMessageDialog(null, ""+X.getValue(0,2), "test", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_startFEMActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton startFEM;
    // End of variables declaration//GEN-END:variables
    
}
